### ISSUE TITLE
Bug: links with # are not well resolved

### ISSUE THREAD

**Issue by ferreiro** [alanshaw/markdown-pdf#116] opened 2017-05-11 19:58 UTC
Hello guys,

Inner links are not well translated when exporting to pdf. Let's suppose we have this markdown:

```
- [Motivation](#motivation)
 - [product](#product)
```

When generating the pdf, those links are pointing to the intermediate HTML that markdown-pdf uses before creating the final pdf:

<img width="477" alt="screen shot 2017-05-11 at 9 53 40 pm" src="https://cloud.githubusercontent.com/assets/7242959/25969249/94bdfd92-3694-11e7-9a6f-edd3a26cbb6f.png">

How can  we fix this? 
If you can give me some ideas I'll work on this issue

**Comment by ferreiro** [comment] 2017-05-11 20:23
@alanshaw Hey Alan, could you give me some clue/insights on this issue?

**Comment by anko** [comment] 2017-05-14 18:47
I think this is a duplicate of https://github.com/alanshaw/markdown-pdf/issues/66. As I summarised in [a comment there](https://github.com/alanshaw/markdown-pdf/issues/66#issuecomment-176790081), this is a PhantomJS limitation. The underlying issue is tracked upstream here: https://github.com/ariya/phantomjs/issues/13959.

**Comment by anko** [comment] 2017-05-14 18:52
Closing in favour of #66.

**Closed by anko** 2017-05-14 18:52 UTC
