### ISSUE TITLE
Unable to jump to a specific section in the generated PDF file.

### ISSUE THREAD

**Issue by PradyumnaR** [alanshaw/markdown-pdf#126] opened 2017-07-31 22:56 UTC
My Markdown has the following html code:
```
<a name="top"></a>
.
.
.
<a href="#top">TOP</a>
```

when I click on  the **TOP**  inside pdf I was not able to jump to that particular section.
But the intermediate html file was able to successfully jump to that particular section when opened in the browser.

thanks for the help in advance.

**Comment by anko** [comment] 2017-08-01 16:16
Duplicate of #66. This is not currently possible. See that thread for status and potential workarounds.

**Closed by anko** 2017-08-01 16:16 UTC
