### ISSUE TITLE
Links are not created as links

### ISSUE THREAD

**Issue by sanitz** [alanshaw/markdown-pdf#30] opened 2014-05-16 10:24 UTC
When I use links in markdown with the syntax ```[description](url)``` I only get blue highlighted text in the pdf, but not the actual link.

**Comment by JonathanMH** [comment] 2015-01-22 09:52
+1

**Comment by andyinabox** [comment] 2015-01-24 23:15
+1 yeah this is a real bummer, not being able to use links with the expected behavior out of the box.

**Comment by brunowego** [comment] 2015-03-24 14:39
+1

**Comment by mamachanko** [comment] 2015-05-04 17:44
+1

**Comment by danielbayley** [comment] 2015-07-08 19:35
As pointed out above, the full URL appearing in brackets is only down to the CSS `content:` rule/s, which can easily be overridden with your own CSS. The issue is that the links don't work. According to that PhantomJS issue thread, It looks like someone has actually fixed this now, but it's waiting to be pulled in. Could we get an update on here when it has please?

**Comment by anko** [comment] 2015-09-18 09:46
Could this issue be reopened? Upstream limitations that cause problems are still *limitations that cause problems* and should be tracked.

I didn't initially notice #63 was about this, because this was closed…

**Comment by biofractal** [comment] 2015-09-18 13:50
If I read it correctly then the PhantomJS issue at the root of the problem looks like it may well have been fixed: [phantomjs/issues/10196](https://github.com/ariya/phantomjs/issues/10196)?

**Comment by anko** [comment] 2015-09-18 14:11
@biofractal

This PR ariya/phantomjs#13250 is supposedly a fix, but it hasn't been merged and maintainers haven't commented—likely because PhantomJS is primarily a headless browser, which only happens to have a PDF renderer, so their priorities are elsewhere. The patch's author [mentions that a Windows binary is available](https://github.com/ariya/phantomjs/pull/13250#issuecomment-125134534), else compile from source.

Another alternative might be [wkpdftohtml](http://wkhtmltopdf.org/) built with their Qt patches, which claims it can do links correctly. I tested the package in the Arch Linux repositories, and found it to have been built to the usual unpatched QtWebkit, and hence unable to create links in PDF. So again, have to compile from source.

Haven't tested either yet.

**Comment by biofractal** [comment] 2015-09-18 14:34
That is the can of worms officially opened - I have gone from idly wondering how to apply a CSS fix to compiling un-merged binaries from projects that are two upstreams removed. One more and we will be compiling Kevin Bacon from source.  

I can see the argument that the link url _should_ be rendered beside the link text because PDFs are intended for printing. At least I have a tech-excuse I can now wave at the punters. Still, links that don't work at all just because they look different is probably not too clever. 

I will keep an eye on this and await developments.

**Comment by danielbayley** [comment] 2015-09-18 14:58
> One more and we will be compiling Kevin Bacon from source.

LOL

> I can see the argument that the link url should be rendered beside the link text because PDFs are intended for printing.

Not at all always; there are plenty of situations where a PDF is intended only for [digital] presentation. Brand guidelines generated from the actual related web stylesheets say, for one example…

**Comment by jasonb-vbt** [comment] 2015-11-11 18:07
+1 to all of this. I accept that it's a phantomJS issue, but jeez, they coudl at least give us some kind of option to control the link formatting.

**Comment by ulidtko** [comment] 2015-12-03 00:18
Still not solved? This issue is horrible!

**Comment by dotmagic** [comment] 2015-12-26 22:50
As pointed out from @alanshaw  its just a insane HTML5 Boildplate default for print styles. Just overwrite with your own CSS. For make any URL auto linked use linkable: true

```CSS
a[href]:after {
	content: "";
}

abbr[title]:after {
	content: "";
}
```

```JS
.pipe(markdownpdf({
	cssPath:  'css/your-css-file.css',
	remarkable: {
		linkify: true,
	}
}))
```

**Comment by marinaserranomontes** [comment] 2016-01-18 10:37
@alanshaw any update about how a "[description](url)" line from a markdown file works in a converted pdf? Thanks

**Comment by alanshaw** [comment] 2016-01-18 10:45
Description line?

**Comment by belyan** [comment] 2016-01-28 09:25
Root cause of the problem was fixed in QT and included in release version 5.6:
https://bugreports.qt.io/browse/QTBUG-44563

Fix from QT was merged to PhantomJS and included in **Release 2.1**:
https://github.com/ariya/phantomjs/issues/10196

@alanshaw Please, update PhantomJS to version 2.1 in your plugin. This will fix the problem with hyperlinks.

**Closed** 2016-01-28 16:03 UTC

**Comment by jasonb-vbt** [comment] 2016-01-28 18:57
Did anyone try this out? I did an `npm update -g markdown-pdf`, and so far as I can tell I now have v7.0.0, with phantomjs-prebuilt 2.1.3 under the covers, yet my PDFs still have un-clickable links. @belyan, @alanshaw, are there any other special steps I need to take?

**Comment by anko** [comment] 2016-01-28 20:08
@jasonb-vbt 

As mentioned in #80, I found it to work on Linux.

Some things to check:

 - Does `markdown-pdf --version` say `7.0.0`?
 - Do your URIs start with `http://` or `https://` at the start?
   `[link text](https://github.com)` works for me, but
   `[link text](github.com)` doesn't.
 - Are you perhaps using the `--phantom-path` flag to point to an old `phantomjs` binary?

If still no cake:

 - Do you also have a `phantomjs` binary installed separately, with `phantomjs --version` `2.1.1` or greater? (The `phantomjs-prebuilt` package *should* correctly detect that and use it, but maybe something weird is going on.)
 - What OS are you on?
 - What PDF reader are you using? (I tested with [zathura](https://pwmt.org/projects/zathura/) and [Google Drive](https://drive.google.com/).)
 - Could you post a [simple test case](http://stackoverflow.com/help/mcve)?

**Comment by belyan** [comment] 2016-01-28 23:11
@anko Thank you for the quick feedback and the new release. I checked it - hyperlinks now work.
OS - Windows 7 SP1
PDF Reader - Adobe Reader 11.0.3

**Comment by jasonb-vbt** [comment] 2016-01-28 23:17
Thanks, all. I seem to have two installations of markdown-pdf on my machine. Not sure how that happened, but yeah, it was looking at the old one.

**Comment by anko** [comment] 2016-01-28 23:30
@belyan And thank *you* for the heads-up on Phantom's update. The release was all @alanshaw though; I only PR'd with a 2-line diff! :stuck_out_tongue:

@jasonb-vbt Perhaps you [changed the global install directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions) between installs. Good to hear it works now.

**Comment by Nikolay-Kha** [comment] 2016-10-24 16:58
Hello!
I still have such issue on linux mint 18 (i.e. ubuntu 16.04).
```
$ phantomjs -v
2.1.1
$ markdown-pdf --version
7.0.0
```
Command line for generating pdf is: `markdown-pdf DeviceHiveESP8266.md -o $BUILD/DeviceHiveESP8266.pdf` so there is no specified phantom path. I looked on output PDF with Xreader, google docs and even on another computer. Links like:
```
[Overview](#overview)
```
become links to <full original md document dir>/markdown-pdf.html and they don't work in viewers.
My MD file - https://github.com/devicehive/esp8266-firmware/blob/develop/DeviceHiveESP8266.md

![image](https://cloud.githubusercontent.com/assets/8740775/19655371/48cd1b96-9a24-11e6-9185-1a6d1ef91602.png)

**Comment by anko** [comment] 2016-10-29 16:09
@Nikolay-Kha I think #66 is the issue you're hitting. Intra-document links (like to `#overview`) are rendered as links, but not to the right place.

**Comment by Nikolay-Kha** [comment] 2016-10-31 09:58
@anko Thank you for pointing it out. That is exactly my case. Hope phantomjs will add fragment identifiers support.
